### PR TITLE
Added 'active' class support for currently visible items.

### PR DESCRIPTION
**Pull request by nikuda**
Works for 1 or many items per page.

### CODE REVIEW

**Comment by nemeseri** [comment]
Why do you need this? Could you provide a use case?
You can always get the active elements through the API. You can get the cursor position and the page size.
Also I can't see why would you need different style for visible elements?

So please provide an example. Thanks

**Comment by nikuda** [comment]
In case you want to show edges of previous and next items, with different styling. It's also good if you want to use css transitions on elements that are coming onto the page; ie fading in as they're coming in, which would get triggered by the setting of the class.

It should be optional perhaps if you define a class name to be used for active:

```
$(".carousel").carousel({
    active: '.active'
});
```

**Comment by nemeseri** [comment]
Merged, thanks for your contribution.
Also I think that the extra if statement is unnecessary (where you create a separate block for 1 item pages), but I left it there you might have a good reason for it.

**Comment by nikuda** [comment]
Thanks Andras.

I'm not getting the new code in ender yet, do you need to republish to npm?

Main reason for that block is dom performance. As it's easy to get the previous item id we can target that html element directly instead of doing it on all elements like we do in the else block. I'll do some tests on this and improve it if necessary.

**Comment by nemeseri** [comment]
Oh. I forgot to publish the package to npm. Now it's published, so you can get it through npm.

**Pull request merged**
